parameters:
    dothiv_contentful.controller.webhook.class: Dothiv\Bundle\ContentfulBundle\Controller\WebhookController
    dothiv_contentful.controller.page.class: Dothiv\Bundle\ContentfulBundle\Controller\PageController

services:
    dothiv_contentful.controller.webhook:
        class: %dothiv_contentful.controller.webhook.class%
        arguments:
         - @dothiv_contentful.repo.content_type
         - @dothiv_contentful.event_dispatcher
         - @doctrine.orm.entity_manager
        calls:
         - [ setLogger, [@logger] ]
