parameters:
    dothiv_contentful.sync.content_type_listener.class: Dothiv\ContentfulBundle\Listener\SyncContentType
    dothiv_contentful.delete.content_type_listener.class: Dothiv\ContentfulBundle\Listener\DeleteContentType
    dothiv_contentful.sync.entry_sync_listener.class: Dothiv\ContentfulBundle\Listener\SyncEntry
    dothiv_contentful.sync.entry_delete_listener.class: Dothiv\ContentfulBundle\Listener\DeleteEntry
    dothiv_contentful.sync.asset_listener.class: Dothiv\ContentfulBundle\Listener\SyncAsset

services:
    dothiv_contentful.sync.content_type_listener:
            class: %dothiv_contentful.sync.content_type_listener.class%
            arguments:
                - @dothiv_contentful.repo.content_type
                - @dothiv_contentful.repo.entry
            tags:
                - { name: kernel.event_listener, event: contentful.contenttype.sync, method: onContentTypeSync }
                - { name: kernel.event_listener, event: contentful.contenttype.sync.all, method: onContentTypesSync }

    dothiv_contentful.delete.content_type_listener:
            class: %dothiv_contentful.delete.content_type_listener.class%
            arguments:
                - @dothiv_contentful.repo.content_type
                - @dothiv_contentful.repo.entry
            tags:
                - { name: kernel.event_listener, event: contentful.contenttype.delete, method: onContentTypeDelete }

    dothiv_contentful.sync.entry_sync_listener:
            class: %dothiv_contentful.sync.entry_sync_listener.class%
            arguments:
                - @dothiv_contentful.repo.entry
            tags:
                - { name: kernel.event_listener, event: contentful.entry.sync, method: onEntrySync }

    dothiv_contentful.sync.entry_delete_listener:
            class: %dothiv_contentful.sync.entry_delete_listener.class%
            arguments:
                - @dothiv_contentful.repo.entry
            tags:
                - { name: kernel.event_listener, event: contentful.entry.delete, method: onEntryDelete }

    dothiv_contentful.sync.asset_listener:
            class: %dothiv_contentful.sync.asset_listener.class%
            arguments:
                - @dothiv_contentful.repo.asset
            tags:
                - { name: kernel.event_listener, event: contentful.asset.sync, method: onAssetSync }
